<?php

namespace Database\Seeders;

use App\Models\Collaboration;
use Illuminate\Database\Seeder;

class CollaborationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $collaborations = [
            [
                'slug' => 'kemitraan',
                'title_id' => 'Kemitraan Strategis',
                'title_en' => 'Strategic Partnership',
                'badge_id' => 'KORPORASI & PEMERINTAH',
                'badge_en' => 'CORPORATE & GOVERNMENT',
                'subtitle_id' => 'Sinergi multipihak untuk hilirisasi teknologi dan pemberdayaan nasional.',
                'subtitle_en' => 'Multi-stakeholder synergy for technology transfer and national empowerment.',
                'description_id' => 'YOIN membuka pintu kolaborasi strategis dengan institusi pemerintahan, BUMN, korporasi swasta, dan asosiasi industri dalam mewujudkan ekosistem inovasi berdaya saing global.',
                'description_en' => 'YOIN welcomes strategic collaboration with government institutions, state-owned enterprises, private corporations, and industry associations.',
                'terms_id' => [
                    'Entitas berbadan hukum resmi (PT, Yayasan, BUMN, Lembaga Pemerintah, atau Koperasi).',
                    'Memiliki rekam jejak kepatuhan tata kelola (Good Corporate Governance) dan integritas operasional.',
                    'Keselarasan komitmen terhadap kedaulatan teknologi nasional dan dampak keberlanjutan ESG.',
                    'Bersedia menandatangani Nota Kesepahaman (MoU) dan Perjanjian Kerja Sama (PKS) resmi.',
                ],
                'terms_en' => [
                    'Formally registered legal entity (Corporation, Foundation, State Agency, or Cooperative).',
                    'Proven track record in good corporate governance and operational integrity.',
                    'Alignment of commitment to national tech sovereignty and ESG sustainability impact.',
                    'Willingness to sign official Memorandum of Understanding (MoU) and Collaboration Agreement.',
                ],
                'requirements_id' => [
                    'Profil Perusahaan / Institusi (Company Profile) terbaru.',
                    'Surat Minat Kemitraan resmi bertandatangan pimpinan.',
                    'Ringkasan eksekutif rencana atau area kerja sama (Scope of Synergy).',
                    'Kontak resmi Pejabat Penghubung (Person-in-Charge / PIC).',
                ],
                'requirements_en' => [
                    'Latest Company Profile / Institutional Overview.',
                    'Official Letter of Intent signed by executive leadership.',
                    'Executive summary of proposed partnership scope.',
                    'Official contact details of designated Person-in-Charge (PIC).',
                ],
                'steps_id' => [
                    ['step' => '01', 'title' => 'Penyusunan Berkas', 'desc' => 'Lengkapi Company Profile dan Surat Minat Kemitraan sesuai format instansi.'],
                    ['step' => '02', 'title' => 'Pengajuan via Email', 'desc' => 'Kirim berkas ke hello@yotainovasi.id dengan subjek [KEMITRAAN] - Nama Instansi.'],
                    ['step' => '03', 'title' => 'Review & Asesmen', 'desc' => 'Tim Kemitraan Strategis YOIN menelaah portofolio sinergi dalam 3-5 hari kerja.'],
                    ['step' => '04', 'title' => 'Sesi Penjajakan (Exploratory Meeting)', 'desc' => 'Pertemuan daring atau tatap muka untuk mematangkan ruang lingkup dan proyeksi dampak.'],
                    ['step' => '05', 'title' => 'Formalisasi MoU / PKS', 'desc' => 'Penandatanganan dokumen legal dan penetapan roadmap kerja sama resmi.'],
                ],
                'steps_en' => [
                    ['step' => '01', 'title' => 'Document Preparation', 'desc' => 'Prepare Company Profile and Official Letter of Intent.'],
                    ['step' => '02', 'title' => 'Email Submission', 'desc' => 'Send documents to hello@yotainovasi.id with subject [PARTNERSHIP] - Institution Name.'],
                    ['step' => '03', 'title' => 'Review & Assessment', 'desc' => 'YOIN Strategic Partnership team reviews synergy potential within 3-5 working days.'],
                    ['step' => '04', 'title' => 'Exploratory Meeting', 'desc' => 'Online or in-person discussion to finalize project scope and mutual impact.'],
                    ['step' => '05', 'title' => 'MoU / Agreement Execution', 'desc' => 'Legal signing and official roadmap implementation.'],
                ],
                'email_to' => 'hello@yotainovasi.id',
                'email_subject' => '[PENGAJUAN KEMITRAAN] - [Nama Perusahaan/Instansi Anda]',
                'email_template' => "Yth. Pimpinan Kemitraan Strategis YOIN Inovasi Nusantara,\n\nKami dari [Nama Perusahaan/Instansi] bermaksud mengajukan penjajakan kemitraan strategis dengan ekosistem YOIN di bidang [Sebutkan Bidang: Misal Teknologi / Riset / ESG].\n\nBersama ini kami lampirkan:\n1. Company Profile Instansi\n2. Surat Pengantar / Minat Kemitraan\n3. Ringkasan Ruang Lingkup Kolaborasi\n\nNarahubung Resmi (PIC):\nNama: [Nama PIC]\nJabatan: [Jabatan]\nNo. HP/WhatsApp: [Nomor Kontak]\n\nAtas perhatian dan kerja sama yang baik, kami ucapkan terima kasih.",
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'slug' => 'magang',
                'title_id' => 'Program Magang & Talenta',
                'title_en' => 'Internship & Talent Program',
                'badge_id' => 'MAHASISWA & FRESH GRADUATE',
                'badge_en' => 'STUDENTS & FRESH GRADUATES',
                'subtitle_id' => 'Eksplorasi proyek nyata kedaulatan teknologi dengan bimbingan mentor ahli.',
                'subtitle_en' => 'Hands-on experience in tech sovereignty projects mentored by industry leaders.',
                'description_id' => 'Program magang intensif 3 hingga 6 bulan yang dirancang untuk mengasah talenta muda nusantara dalam rekayasa perangkat lunak, riset kecerdasan buatan, operasional lapangan, dan komunikasi publik.',
                'description_en' => 'An intensive 3 to 6-month internship crafted to sharpen young talents in software engineering, applied AI research, and ecosystem operations.',
                'terms_id' => [
                    'Mahasiswa aktif minimal semester 5 atau lulusan baru (Fresh Graduate maks. 1 tahun).',
                    'Memiliki integritas tinggi, kedisiplinan kerja, dan motivasi belajar mandiri yang kuat.',
                    'Dapat berkomitmen penuh waktu (Full-time) atau paruh waktu (Part-time) selama periode magang.',
                    'Mampu bekerja dalam tim multidisiplin secara luring (Bandung) atau sistem kerja terdistribusi (Remote).',
                ],
                'terms_en' => [
                    'Active university students (min. 5th semester) or fresh graduates (within 1 year of graduation).',
                    'High integrity, strong work ethic, and proactive continuous learning mindset.',
                    'Available for full-time or approved part-time commitment during the program.',
                    'Capable of multidisciplinary teamwork onsite (Bandung) or distributed hybrid setup.',
                ],
                'requirements_id' => [
                    'Curriculum Vitae (CV) terbaru dan ringkas.',
                    'Portofolio karya, proyek GitHub, desain, atau publikasi tulisan terkait.',
                    'Surat Pengantar Magang dari Fakultas / Kampus (dapat menyusul saat lolos).',
                    'Transkrip nilai akademik terbaru.',
                    'Surat motivasi singkat (Cover Letter) maksimal 1 halaman.',
                ],
                'requirements_en' => [
                    'Latest concise Curriculum Vitae (CV).',
                    'Portfolio of past projects, GitHub repository, design deck, or writings.',
                    'Official university internship recommendation letter (can follow after acceptance).',
                    'Latest academic transcript.',
                    'Brief statement of purpose (Cover Letter, max 1 page).',
                ],
                'steps_id' => [
                    ['step' => '01', 'title' => 'Penyiapan Berkas', 'desc' => 'Satukan CV, portofolio karya terbaik, dan transkrip nilai dalam format PDF.'],
                    ['step' => '02', 'title' => 'Kirim Berkas via Email', 'desc' => 'Kirim email ke hello@yotainovasi.id dengan subjek [MAGANG] - Nama Lengkap - Posisi/Minat.'],
                    ['step' => '03', 'title' => 'Seleksi Administratif', 'desc' => 'Pemeriksaan berkas dan portofolio oleh tim People & Culture YOIN.'],
                    ['step' => '04', 'title' => 'Wawancara & Studi Kasus', 'desc' => 'Sesi diskusi mendalam mengenai aspirasi proyek dan pemecahan masalah praktis.'],
                    ['step' => '05', 'title' => 'Offering & Onboarding', 'desc' => 'Penerimaan surat penawaran magang resmi dan induksi orientasi ekosistem.'],
                ],
                'steps_en' => [
                    ['step' => '01', 'title' => 'Document Package', 'desc' => 'Assemble your CV, project portfolio, and transcript into clean PDF files.'],
                    ['step' => '02', 'title' => 'Email Application', 'desc' => 'Send email to hello@yotainovasi.id with subject [INTERNSHIP] - Full Name - Role/Field.'],
                    ['step' => '03', 'title' => 'Administrative Screening', 'desc' => 'CV and portfolio evaluation by YOIN People & Culture team.'],
                    ['step' => '04', 'title' => 'Interview & Practical Case', 'desc' => 'In-depth discussion on project aspirations and practical problem-solving.'],
                    ['step' => '05', 'title' => 'Offering & Induction', 'desc' => 'Official acceptance letter issuance and ecosystem onboarding orientation.'],
                ],
                'email_to' => 'hello@yotainovasi.id',
                'email_subject' => '[PENGAJUAN MAGANG] - [Nama Lengkap] - [Posisi/Divisi yang Diminati]',
                'email_template' => "Yth. Tim People & Culture YOIN Inovasi Nusantara,\n\nPerkenalkan saya [Nama Lengkap], mahasiswa/lulusan dari [Nama Universitas / Jurusan]. Saya bermaksud mengajukan diri untuk mengikuti Program Magang di YOIN untuk posisi [Sebutkan: Software Engineering / AI Research / Content & Media / Business Development / Operasional].\n\nBersama ini saya lampirkan dokumen pendukung:\n1. Curriculum Vitae (CV)\n2. Portofolio Proyek / Karya\n3. Transkrip Nilai Akademik Terakhir\n4. Surat Motivasi Diri Singkat\n\nPeriode Magang yang diharapkan: [Contoh: Oktober 2026 - Januari 2027]\nNo. HP/WhatsApp: [Nomor Kontak]\nLinkedIn/GitHub: [Tautan Profil]\n\nBesar harapan saya untuk dapat berkontribusi dalam inisiatif kedaulatan nusantara bersama YOIN. Terima kasih.",
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'slug' => 'riset',
                'title_id' => 'Kolaborasi Riset & Studi Terapan',
                'title_en' => 'Research & Applied Studies',
                'badge_id' => 'PENELITI & AKADEMISI',
                'badge_en' => 'RESEARCHERS & ACADEMIA',
                'subtitle_id' => 'Pusat integrasi penelitian bersama universitas, saintis, dan lembaga riset independen.',
                'subtitle_en' => 'Collaborative research hub integrating universities, scientists, and independent institutes.',
                'description_id' => 'YOIN memfasilitasi riset bersama (Joint Research) dan hilirisasi saintifik di bidang kecerdasan buatan, teknologi maritim, ketahanan pangan kepulauan, serta efisiensi energi terbarukan.',
                'description_en' => 'Facilitating joint research, open data access, and scientific commercialization in applied AI, maritime systems, and sustainable island ecosystems.',
                'terms_id' => [
                    'Peneliti independen, dosen, mahasiswa pascasarjana, atau kelompok riset terafiliasi resmi.',
                    'Fokus tema riset selaras dengan pilar ekosistem YOIN (Teknologi, Lingkungan, Agrikultur, Kebijakan Publik).',
                    'Menjunjung tinggi etika penelitian, kejujuran ilmiah, serta keterbukaan metodologi data.',
                    'Berorientasi pada luaran nyata (Paper Terindeks, Prototipe Teruji, atau Kebijakan Solutif).',
                ],
                'terms_en' => [
                    'Independent researchers, faculty members, graduate scholars, or affiliated research groups.',
                    'Research focus aligned with YOIN pillars (Technology, Ecology, Agriculture, Public Policy).',
                    'Adherence to ethical scientific standards and transparent data methodology.',
                    'Targeting tangible deliverables (Indexed Papers, Tested Prototypes, or Actionable Policy Frameworks).',
                ],
                'requirements_id' => [
                    'Ringkasan Eksekutif Proposal Riset (Latar belakang, rumusan masalah, metodologi, dan linimasa).',
                    'Daftar Peneliti Utama dan Curriculum Vitae anggota tim.',
                    'Kebutuhan dukungan yang diharapkan (Fasilitas riset, akses data lapangan, atau pendanaan bersama).',
                    'Surat Rekomendasi atau Pengantar dari Lembaga Riset / Dekanat terkait.',
                ],
                'requirements_en' => [
                    'Research Proposal Executive Summary (Background, methodology, timeline, and deliverables).',
                    'Principal Investigator roster and team Curriculum Vitae.',
                    'Support requested (Field facilities, data infrastructure, or joint co-funding).',
                    'Official endorsement letter from University / Faculty Research Board.',
                ],
                'steps_id' => [
                    ['step' => '01', 'title' => 'Penyusunan Proposal', 'desc' => 'Susun ringkasan metodologi riset dan target luaran ilmiah terapan.'],
                    ['step' => '02', 'title' => 'Pengajuan via Email', 'desc' => 'Kirim proposal ke hello@yotainovasi.id dengan subjek [KOLABORASI RISET] - Judul Riset - Lembaga.'],
                    ['step' => '03', 'title' => 'Review Dewan Riset YOIN', 'desc' => 'Telaah kelayakan teknis dan dampak strategis oleh Tim Riset & Jurnal YOIN.'],
                    ['step' => '04', 'title' => 'Focus Group Discussion (FGD)', 'desc' => 'Penyelarasan ruang lingkup riset, pembagian peran, dan fasilitas pendukung.'],
                    ['step' => '05', 'title' => 'Perjanjian Riset Bersama', 'desc' => 'Penetapan Joint Research Agreement dan jadwal implementasi riset lapangan.'],
                ],
                'steps_en' => [
                    ['step' => '01', 'title' => 'Proposal Formulation', 'desc' => 'Draft research methodology and tangible applied deliverables.'],
                    ['step' => '02', 'title' => 'Email Submission', 'desc' => 'Send proposal to hello@yotainovasi.id with subject [RESEARCH COLLABORATION] - Title - Institution.'],
                    ['step' => '03', 'title' => 'YOIN Scientific Review', 'desc' => 'Technical evaluation and strategic impact assessment by YOIN Research Council.'],
                    ['step' => '04', 'title' => 'Focus Group Discussion (FGD)', 'desc' => 'Aligning research boundaries, roles, and resource allocation.'],
                    ['step' => '05', 'title' => 'Joint Research Agreement', 'desc' => 'Formalizing agreement terms and launching field study milestones.'],
                ],
                'email_to' => 'hello@yotainovasi.id',
                'email_subject' => '[PENGAJUAN RISET] - [Judul Riset] - [Lembaga/Kampus]',
                'email_template' => "Yth. Dewan Riset & Publikasi YOIN Inovasi Nusantara,\n\nKami dari [Kelompok Riset / Lembaga / Laboratorium Kampus] bermaksud mengajukan proposal kolaborasi riset bersama YOIN dengan judul:\n\"[Tuliskan Judul Riset Anda]\"\n\nTema Fokus: [Sebutkan: Teknologi Presisi / Kelautan & Maritim / Energi Hijau / Sosial Kebijakan]\n\nBersama ini kami lampirkan:\n1. Ringkasan Eksekutif Proposal Riset (PDF)\n2. CV Peneliti Utama & Anggota Tim\n3. Surat Rekomendasi Lembaga / Dekanat\n\nPeneliti Utama (PI):\nNama: [Nama Peneliti]\nJabatan & Afiliasi: [Jabatan & Institusi]\nKontak Email & HP: [Kontak]\n\nBesar harapan kami dapat berkolaborasi memajukan riset terapan nusantara bersama YOIN. Terima kasih.",
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'slug' => 'kunjungan',
                'title_id' => 'Kunjungan Industri & Edukasi',
                'title_en' => 'Industrial & Institutional Visits',
                'badge_id' => 'DELEGASI KAMPUS & KOMUNITAS',
                'badge_en' => 'DELEGATIONS & INSTITUTIONS',
                'subtitle_id' => 'Studi komparatif langsung ke pusat riset, ekosistem teknologi, dan kantor operasional YOIN.',
                'subtitle_en' => 'Field immersion and benchmarking at YOIN innovation labs and operational hubs.',
                'description_id' => 'Menyambut delegasi universitas, sekolah kejuruan, lembaga pemerintahan, dan asosiasi profesional untuk berdiskusi, memahami alur kerja rekayasa teknologi, serta melihat langsung inisiatif kemandirian YOIN.',
                'description_en' => 'Welcoming university student chapters, vocational schools, and institutional delegations for interactive tech benchmarking and lab tours.',
                'terms_id' => [
                    'Rombongan delegasi resmi berasal dari institusi pendidikan, kedinasan, atau komunitas berbadan hukum.',
                    'Jumlah peserta kunjungan antara 10 hingga 40 orang per sesi untuk memastikan kenyamanan dialog interaktif.',
                    'Permohonan diajukan minimal 14 hari kerja (H-14) sebelum tanggal rencana kunjungan.',
                    'Mematuhi tata tertib, regulasi keselamatan, dan etika dokumentasi di fasilitas YOIN.',
                ],
                'terms_en' => [
                    'Official delegations from accredited academic institutions, government bodies, or verified organizations.',
                    'Group capacity between 10 to 40 participants per session to ensure meaningful interactive dialogue.',
                    'Applications submitted at least 14 working days (H-14) prior to requested date.',
                    'Compliance with safety standards, facility regulations, and confidentiality protocols.',
                ],
                'requirements_id' => [
                    'Surat Permohonan Kunjungan Resmi berkop surat dan berstempel instansi.',
                    'Daftar nama delegasi, pendamping / dosen pembimbing, dan kontak koordinator rombongan.',
                    'Maksud, tujuan, dan topik utama yang ingin didalami dalam sesi kunjungan.',
                    'Opsi 2-3 alternatif tanggal dan jadwal kunjungan yang diusulkan.',
                ],
                'requirements_en' => [
                    'Official Visit Request Letter on institutional letterhead with executive stamp.',
                    'List of delegation participants, chaperones, and lead coordinator contacts.',
                    'Clear statement of purpose and primary topics of interest.',
                    '2-3 proposed alternative visit dates and timeframe.',
                ],
                'steps_id' => [
                    ['step' => '01', 'title' => 'Penerbitan Surat Resmi', 'desc' => 'Dapatkan surat permohonan kunjungan berkop instansi resmi bertandatangan pimpinan.'],
                    ['step' => '02', 'title' => 'Pengiriman Email', 'desc' => 'Kirim surat ke hello@yotainovasi.id dengan subjek [KUNJUNGAN INDUSTRI] - Nama Lembaga - Opsi Tanggal.'],
                    ['step' => '03', 'title' => 'Konfirmasi Jadwal', 'desc' => 'Tim Humas & Operasional YOIN memverifikasi ketersediaan ruang dan narasumber (2-3 hari kerja).'],
                    ['step' => '04', 'title' => 'Surat Balasan & Briefing', 'desc' => 'Penerbitan surat persetujuan, agenda rundown resmi, dan protokol tata tertib fasilitas.'],
                    ['step' => '05', 'title' => 'Pelaksanaan Kunjungan', 'desc' => 'Kunjungan interaktif, presentasi teknologi, sesi tanya jawab, dan penyerahan plakat/cendera mata.'],
                ],
                'steps_en' => [
                    ['step' => '01', 'title' => 'Official Letter Issuance', 'desc' => 'Obtain signed official letter from university or institutional leadership.'],
                    ['step' => '02', 'title' => 'Email Dispatch', 'desc' => 'Send letter to hello@yotainovasi.id with subject [INDUSTRIAL VISIT] - Institution - Dates.'],
                    ['step' => '03', 'title' => 'Schedule Verification', 'desc' => 'YOIN Public Relations team checks calendar and host availability (2-3 business days).'],
                    ['step' => '04', 'title' => 'Formal Acceptance & Brief', 'desc' => 'Issuance of confirmation letter, official itinerary rundown, and security guidelines.'],
                    ['step' => '05', 'title' => 'Event Execution', 'desc' => 'Interactive session, technology walkthrough, Q&A discussion, and memento exchange.'],
                ],
                'email_to' => 'hello@yotainovasi.id',
                'email_subject' => '[PERMOHONAN KUNJUNGAN] - [Nama Lembaga/Kampus] - [Tanggal Rencana]',
                'email_template' => "Yth. Tim Humas & Hubungan Kelembagaan YOIN Inovasi Nusantara,\n\nKami dari [Nama Institusi / Fakultas / Komunitas] bermaksud mengajukan permohonan Kunjungan Industri / Studi Banding ke kantor dan fasilitas riset YOIN.\n\nDetail Rencana Kunjungan:\n- Estimasi Jumlah Peserta: [Contoh: 25 Orang (20 Mahasiswa + 5 Dosen Pembimbing)]\n- Opsi Tanggal Pilihan 1: [Tanggal]\n- Opsi Tanggal Pilihan 2: [Tanggal Alternatif]\n- Topik Pembahasan yang Diharapkan: [Contoh: Implementasi IoT & AI Lapangan, Kultur Kerja Inovasi]\n\nBersama ini kami lampirkan:\n1. Surat Resmi Permohonan Kunjungan (Kop & Stempel Institusi)\n2. Daftar Rombongan Delegasi\n\nKoordinator Rombongan (PIC):\nNama: [Nama Koordinator]\nJabatan: [Jabatan / Perwakilan Dosen/Himpunan]\nNo. HP/WhatsApp: [Nomor Kontak]\n\nAtas kerja sama dan sambutan hangat dari YOIN, kami sampaikan terima kasih.",
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'slug' => 'kegiatan',
                'title_id' => 'Kolaborasi Kegiatan & Event',
                'title_en' => 'Events & Community Collaborations',
                'badge_id' => 'SEMINAR, WORKSHOP & HACKATHON',
                'badge_en' => 'SEMINARS, WORKSHOPS & HACKATHONS',
                'subtitle_id' => 'Sinergi penyelenggaraan lokakarya, konferensi, expo riset, dan inisiatif pemberdayaan.',
                'subtitle_en' => 'Joint organization of technology workshops, conferences, expos, and empowerment drives.',
                'description_id' => 'YOIN siap berkolaborasi sebagai mitra penyelenggara (co-host), narasumber ahli, mentor teknis, maupun pendukung strategis pada seminar nasional, hackathon, lokakarya teknologi, dan expo sains nusantara.',
                'description_en' => 'Collaborating as strategic co-host, keynote experts, technical mentors, or community partners for national tech conventions and hackathons.',
                'terms_id' => [
                    'Panitia penyelenggara resmi berasal dari perguruan tinggi, instansi, atau komunitas kreatif terverifikasi.',
                    'Acara memiliki target audiens yang jelas dan memberikan dampak positif pada literasi teknologi atau sains.',
                    'Proposal kegiatan diajukan minimal 21 hari kerja (H-21) sebelum hari pelaksanaan acara.',
                    'Menyediakan skema kerja sama yang transparan (Co-branding, Keynote Speaker, Workshop Mentor, dll).',
                ],
                'terms_en' => [
                    'Organizing committee representing an accredited institution or verified community.',
                    'Event has defined audience targets and positive impact on technology and scientific literacy.',
                    'Proposals submitted at least 21 working days (H-21) prior to event execution.',
                    'Transparent collaboration terms (Co-branding, Keynote, Mentorship, or Logistics).',
                ],
                'requirements_id' => [
                    'Proposal Lengkap Kegiatan / Sponsorship bertandatangan panitia penanggung jawab.',
                    'Rundown acara, profil peserta, dan target capaian kegiatan.',
                    'Daftar narasumber yang diajukan beserta bentuk kontribusi yang diharapkan dari YOIN.',
                    'Materi publikasi awal atau rancangan branding media sosial acara.',
                ],
                'requirements_en' => [
                    'Comprehensive Event & Collaboration Proposal signed by leadership.',
                    'Itinerary rundown, attendee profile projection, and target outcome metrics.',
                    'Requested roles from YOIN (Speaker, panelist, mentor, or booth exhibitor).',
                    'Initial creative branding assets or event promotional campaign draft.',
                ],
                'steps_id' => [
                    ['step' => '01', 'title' => 'Penyusunan Proposal Acara', 'desc' => 'Siapkan proposal terstruktur dengan rundown, target peserta, dan bentuk kerja sama.'],
                    ['step' => '02', 'title' => 'Pengajuan via Email', 'desc' => 'Kirim berkas ke hello@yotainovasi.id dengan subjek [KOLABORASI EVENT] - Nama Kegiatan - Penyelenggara.'],
                    ['step' => '03', 'title' => 'Review Kesiapan & Jadwal', 'desc' => 'Tim Ekosistem YOIN menelaah relevansi tema dan ketersediaan pembicara / dukungan.'],
                    ['step' => '04', 'title' => 'Koordinasi Teknis', 'desc' => 'Diskusi teknis rundown bersama panitia inti dan penyiapan materi presentasi.'],
                    ['step' => '05', 'title' => 'Eksekusi Kegiatan Bersama', 'desc' => 'Pelaksanaan acara secara sukses, promosi silang, dan evaluasi capaian dampak pasca-acara.'],
                ],
                'steps_en' => [
                    ['step' => '01', 'title' => 'Proposal Drafting', 'desc' => 'Prepare structured proposal detailing agenda, reach, and required support.'],
                    ['step' => '02', 'title' => 'Email Submission', 'desc' => 'Send to hello@yotainovasi.id with subject [EVENT COLLABORATION] - Event Name - Host.'],
                    ['step' => '03', 'title' => 'Feasibility Review', 'desc' => 'YOIN Ecosystem team reviews thematic fit and speaker availability.'],
                    ['step' => '04', 'title' => 'Technical Coordination', 'desc' => 'Direct coordination with core organizers to align presentations and media assets.'],
                    ['step' => '05', 'title' => 'Event Rollout', 'desc' => 'Successful co-hosting, cross-promotional reach, and post-event impact recap.'],
                ],
                'email_to' => 'hello@yotainovasi.id',
                'email_subject' => '[KOLABORASI EVENT] - [Nama Acara/Kegiatan] - [Penyelenggara]',
                'email_template' => "Yth. Tim Event & Komunitas YOIN Inovasi Nusantara,\n\nKami dari panitia pelaksana [Nama Acara / Kegiatan] yang diselenggarakan oleh [Nama Lembaga / Himpunan / Komunitas] bermaksud mengajukan kerja sama kolaborasi kegiatan bersama YOIN.\n\nInformasi Acara:\n- Nama Kegiatan: [Nama Acara]\n- Tema: [Tema Acara]\n- Waktu & Tempat: [Tanggal & Lokasi / Platform Virtual]\n- Target Peserta: [Contoh: 300 Mahasiswa & Profesional Teknologi]\n- Bentuk Dukungan yang Diharapkan: [Sebutkan: Pembicara Utama / Mentor Workshop / Media Partner / Co-Branding]\n\nBersama ini kami lampirkan:\n1. Proposal Lengkap Kegiatan (PDF)\n2. Rundown Acara & Lembar Kerja Sama\n\nNarahubung Panitia (PIC):\nNama: [Nama PIC]\nJabatan dalam Panitia: [Jabatan]\nNo. HP/WhatsApp: [Nomor Kontak]\n\nTerima kasih atas kesediaan waktu dan dukungan dari rekan-rekan YOIN.",
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'slug' => 'project',
                'title_id' => 'Proyek Bersama & Solusi Kustom',
                'title_en' => 'Joint Projects & Custom Solutions',
                'badge_id' => 'KONSORSIUM & PENGEMBANGAN TEKNOLOGI',
                'badge_en' => 'CONSORTIUM & TECH DEVELOPMENT',
                'subtitle_id' => 'Pengembangan solusi perangkat lunak enterprise, otomatisasi, dan arsitektur digital terintegrasi.',
                'subtitle_en' => 'Enterprise software engineering, automation workflows, and integrated digital architectures.',
                'description_id' => 'Melayani rekayasa sistem terukur, digitalisasi alur kerja strategis, pembangunan platform data analitik, dan implementasi infrastruktur cerdas untuk mitra bisnis serta instansi strategis.',
                'description_en' => 'Delivering robust system engineering, strategic workflow digitization, intelligent data pipelines, and smart infrastructure deployments for enterprise partners.',
                'terms_id' => [
                    'Klien atau mitra konsorsium memiliki ruang lingkup kebutuhan (Scope of Work / TOR) yang teridentifikasi.',
                    'Memiliki komitmen linimasa (timeline) dan alokasi anggaran proyek yang proporsional.',
                    'Dikelola dengan metodologi agile berbasis milestone pencapaian terukur.',
                    'Penetapan hak kekayaan intelektual (IP Rights) dan kerahasiaan data (NDA) secara tegas dan adil.',
                ],
                'terms_en' => [
                    'Partner has a well-defined Scope of Work (TOR / Technical Requirements).',
                    'Realistic operational timeline and dedicated project capital allocation.',
                    'Governed through agile methodologies with transparent milestone verifications.',
                    'Equitable intellectual property (IP) structuring and mutual Non-Disclosure Agreement (NDA).',
                ],
                'requirements_id' => [
                    'Kerangka Acuan Kerja (KAK) / Terms of Reference (TOR) proyek.',
                    'Dokumen spesifikasi kebutuhan bisnis & teknis (jika sudah ada).',
                    'Target tanggal peluncuran (Expected Delivery Date) dan ekspektasi milestone.',
                    'Kontak Pengambil Keputusan (Project Owner / Technical Decision Maker).',
                ],
                'requirements_en' => [
                    'Terms of Reference (TOR) / Project Charter.',
                    'Business & Technical Requirements Document (if available).',
                    'Target Go-Live milestones and deployment timeframe.',
                    'Contact details for Project Sponsor / Key Technical Decision Maker.',
                ],
                'steps_id' => [
                    ['step' => '01', 'title' => 'Penyusunan KAK / TOR', 'desc' => 'Rumuskan kebutuhan fungsional, sasaran proyek, dan estimasi waktu.'],
                    ['step' => '02', 'title' => 'Pengajuan via Email', 'desc' => 'Kirim KAK ke hello@yotainovasi.id dengan subjek [PROJEK KOLABORASI] - Nama Proyek - Lembaga.'],
                    ['step' => '03', 'title' => 'Asesmen Arsitektur & Biaya', 'desc' => 'Tim Engineering & Solutions YOIN melakukan studi kelayakan teknis dalam 3-4 hari kerja.'],
                    ['step' => '04', 'title' => 'Presentasi Solusi Teknis', 'desc' => 'Pemaparan diagram arsitektur sistem, estimasi sprint, dan proposal komersial.'],
                    ['step' => '05', 'title' => 'Kick-off & Sprint Engineering', 'desc' => 'Penandatanganan kontrak kerja sama dan eksekusi sprint pengembangan perangkat lunak.'],
                ],
                'steps_en' => [
                    ['step' => '01', 'title' => 'TOR Formulation', 'desc' => 'Document functional expectations, system objectives, and deadlines.'],
                    ['step' => '02', 'title' => 'Email Dispatch', 'desc' => 'Send requirements to hello@yotainovasi.id with subject [JOINT PROJECT] - Project Title - Entity.'],
                    ['step' => '03', 'title' => 'Architecture & Feasibility Assessment', 'desc' => 'YOIN Engineering architects conduct feasibility evaluation within 3-4 business days.'],
                    ['step' => '04', 'title' => 'Solution & Architecture Pitch', 'desc' => 'Detailed system blueprints, sprint milestones, and commercial terms presentation.'],
                    ['step' => '05', 'title' => 'Contract Execution & Sprint Kick-off', 'desc' => 'Formal agreement execution and immediate deployment of agile dev sprints.'],
                ],
                'email_to' => 'hello@yotainovasi.id',
                'email_subject' => '[PENGAJUAN PROJEK] - [Nama Proyek/Sistem] - [Perusahaan/Instansi]',
                'email_template' => "Yth. Tim Solusi Teknologi & Rekayasa Sistem YOIN Inovasi Nusantara,\n\nKami dari [Nama Perusahaan / Organisasi] bermaksud mendiskusikan kebutuhan pengerjaan proyek teknologi / rekayasa sistem bersama tim YOIN dengan rincian singkat sebagai berikut:\n\n- Nama Proyek / Inisiatif: [Nama Proyek]\n- Gambaran Umum Kebutuhan: [Jelaskan singkat masalah yang ingin diselesaikan / sistem yang ingin dibangun]\n- Target Mulai & Selesai: [Contoh: November 2026 - Februari 2027]\n- Estimasi Alokasi Anggaran: [Opsi Anggaran]\n\nBersama ini kami lampirkan:\n1. Dokumen KAK / Terms of Reference (TOR)\n2. Sketsa Alur Kerja / Spesifikasi Awal\n\nNarahubung Proyek (Project Owner):\nNama: [Nama PIC]\nJabatan: [Jabatan]\nNo. HP/WhatsApp: [Nomor Kontak]\nEmail Resmi: [Email]\n\nKami menantikan kesempatan berdiskusi teknis lebih lanjut bersama tim ahli YOIN. Terima kasih.",
                'sort_order' => 6,
                'is_active' => true,
            ],
        ];

        foreach ($collaborations as $collab) {
            Collaboration::updateOrCreate(
                ['slug' => $collab['slug']],
                $collab
            );
        }
    }
}
